workflows:
  android-workflow:
    name: Android build
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk